apiVersion: v1
kind: Service
metadata:
  name: api-atlas
  namespace: api-atlas
spec:
  selector:
    app: api-atlas
  ports:
    - name: http
      port: 80
      targetPort: 8080
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: api-atlas
  namespace: api-atlas
spec:
  tls:
    - hosts: [atlas.example.com]
      secretName: api-atlas-tls
  rules:
    - host: atlas.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: api-atlas
                port:
                  number: 80
