# API tests generated by API Atlas

Data-driven REST Assured + TestNG suite (Java 21, Maven). Endpoints are read from `src/test/resources/endpoints.json`.

## Run

```
mvn test                                  # safe (GET/HEAD) endpoints only
mvn test -Dallow.mutating=true            # also POST/PUT/PATCH/DELETE - only against test environments!
mvn test -Denv=qa -Dtoken=<bearer token>  # environment file: src/test/resources/config/<env>.properties
mvn test -DbaseUrl=https://qa.example.com # override the recorded base URL
mvn surefire-report:report                # HTML report in target/site
```

## Suites
- `SmokeTests` - endpoint responds without a 5xx error
- `RegressionTests` - status code equals the recorded status (requires `-Dtoken` for authenticated endpoints)
- `ContractTests` - response content type and JSON validity match the recorded sample
- `NegativeTests` - unauthenticated calls are rejected; malformed identifiers do not cause 5xx
- `BoundaryTests` - extreme identifier values do not cause 5xx

Never commit tokens. Pass them with `-Dtoken` or your CI secret store.
