package com.apiatlas.exporter;

import com.apiatlas.dto.SecurityReportDto;
import com.apiatlas.model.ApiEndpoint;
import com.apiatlas.model.ApiResponse;
import com.apiatlas.model.SecurityFinding;
import lombok.RequiredArgsConstructor;
import org.springframework.stereotype.Component;
import org.springframework.web.util.HtmlUtils;

import java.util.List;
import java.util.Map;
import java.util.stream.Collectors;

/** Self-contained HTML documentation and security report. All dynamic content is HTML-escaped. */
@Component
@RequiredArgsConstructor
public class HtmlExporter {
    private static final String HEAD = "<!DOCTYPE html><html lang=\"en\"><head><meta charset=\"utf-8\">"
            + "<meta http-equiv=\"Content-Security-Policy\" content=\"default-src 'none'; style-src 'unsafe-inline'\">"
            + "<title>%s</title><style>body{font-family:Segoe UI,Arial,sans-serif;margin:2rem;color:#222}"
            + "table{border-collapse:collapse;width:100%%}td,th{border:1px solid #ddd;padding:6px;text-align:left;vertical-align:top}"
            + "th{background:#f3f4f6}pre{background:#f6f8fa;padding:8px;overflow:auto;white-space:pre-wrap}"
            + ".m{font-weight:bold}.sev-HIGH,.sev-CRITICAL{color:#b00020}.sev-MEDIUM{color:#b26a00}</style></head><body>";

    private final EndpointDetails details;

    public String documentation(List<ApiEndpoint> endpoints, String title) {
        StringBuilder h = new StringBuilder(String.format(HEAD, esc(title)));
        h.append("<h1>").append(esc(title)).append("</h1><p>").append(endpoints.size()).append(" APIs. Generated by API Atlas.</p>");
        h.append("<table><tr><th>Method</th><th>Service</th><th>Path</th><th>Auth</th><th>Status</th></tr>");
        for (ApiEndpoint e : endpoints) {
            h.append("<tr><td class=m>").append(esc(e.getMethod())).append("</td><td>").append(esc(e.getService()))
                    .append("</td><td><a href=\"#api").append(e.getId()).append("\">").append(esc(e.getPath()))
                    .append("</a></td><td>").append(e.getAuthType()).append("</td><td>").append(e.getStatus()).append("</td></tr>");
        }
        h.append("</table>");
        for (ApiEndpoint e : endpoints) {
            h.append("<hr><h2 id=\"api").append(e.getId()).append("\">").append(esc(e.getMethod())).append(' ')
                    .append(esc(e.getPath())).append("</h2>");
            h.append("<p><b>URL:</b> ").append(esc(e.getUrl())).append(" &middot; <b>Protocol:</b> ").append(e.getProtocol())
                    .append(" &middot; <b>Version:</b> ").append(esc(e.getVersion())).append("</p>");
            h.append("<p><b>Authentication:</b> ").append(e.getAuthType()).append("</p>");
            section(h, "Description", e.getDescription());
            section(h, "Business purpose", e.getBusinessPurpose());
            section(h, "Request description", e.getRequestDescription());
            section(h, "Response description", e.getResponseDescription());
            Map<String, String> q = details.queryParams(e.getId());
            if (!q.isEmpty()) {
                h.append("<h3>Query parameters</h3><ul>");
                q.forEach((k, v) -> h.append("<li>").append(esc(k)).append(" = ").append(esc(v)).append("</li>"));
                h.append("</ul>");
            }
            if (e.getSampleRequest() != null) h.append("<h3>Request example</h3><pre>").append(esc(e.getSampleRequest())).append("</pre>");
            if (e.getSampleResponse() != null) h.append("<h3>Response example</h3><pre>").append(esc(e.getSampleResponse())).append("</pre>");
            List<ApiResponse> errors = details.responsesByStatus(e.getId()).values().stream().filter(r -> r.getStatusCode() >= 400).toList();
            if (!errors.isEmpty()) {
                h.append("<h3>Error codes</h3><ul>");
                errors.forEach(r -> h.append("<li>").append(r.getStatusCode()).append("</li>"));
                h.append("</ul>");
            }
            section(h, "Test recommendations", e.getTestRecommendations());
        }
        return h.append("</body></html>").toString();
    }

    public String securityReport(SecurityReportDto report) {
        StringBuilder h = new StringBuilder(String.format(HEAD, "API Atlas Security Report"));
        h.append("<h1>Security Report</h1><p>Generated ").append(report.generatedAt()).append(" &middot; ")
                .append(report.totalOpen()).append(" open findings</p>");
        h.append("<p>").append(report.bySeverity().entrySet().stream().map(en -> esc(en.getKey()) + ": " + en.getValue())
                .collect(Collectors.joining(" &middot; "))).append("</p>");
        h.append("<table><tr><th>Severity</th><th>Endpoint</th><th>Category</th><th>OWASP</th><th>Finding</th></tr>");
        for (SecurityFinding f : report.findings()) {
            h.append("<tr><td class=\"sev-").append(f.getSeverity()).append("\">").append(f.getSeverity()).append("</td><td>")
                    .append(esc(f.getEndpointLabel())).append("</td><td>").append(esc(f.getCategory())).append("</td><td>")
                    .append(esc(f.getOwasp())).append("</td><td><b>").append(esc(f.getTitle())).append("</b><br>")
                    .append(esc(f.getDescription())).append("</td></tr>");
        }
        return h.append("</table></body></html>").toString();
    }

    private static void section(StringBuilder h, String title, String text) {
        if (text != null && !text.isBlank()) {
            h.append("<h3>").append(title).append("</h3><p>").append(esc(text).replace("\n", "<br>")).append("</p>");
        }
    }

    private static String esc(String s) {
        return s == null ? "" : HtmlUtils.htmlEscape(s);
    }
}
