package com.apiatlas.exporter;

import com.apiatlas.model.ApiEndpoint;
import com.apiatlas.model.ApiResponse;
import com.apiatlas.model.Enums.AuthType;
import com.apiatlas.utility.PathNormalizer;
import lombok.RequiredArgsConstructor;
import org.springframework.stereotype.Component;

import java.util.*;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

/** Builds an OpenAPI 3.0.3 document from the catalog. */
@Component
@RequiredArgsConstructor
public class OpenApiExporter {
    private static final Pattern PATH_PARAM = Pattern.compile("\\{([^}]+)}");

    private final EndpointDetails details;

    public Map<String, Object> build(List<ApiEndpoint> endpoints, String title) {
        Map<String, Object> root = new LinkedHashMap<>();
        root.put("openapi", "3.0.3");
        root.put("info", Map.of("title", title, "version", "1.0.0", "description", "Generated by API Atlas"));

        Set<String> servers = new LinkedHashSet<>();
        Map<String, Object> paths = new TreeMap<>();
        Set<String> usedSchemes = new TreeSet<>();
        for (ApiEndpoint e : endpoints) {
            servers.add(PathNormalizer.baseUrl(e.getUrl(), e.getPath()));
            Map<String, Object> item = castMap(paths.computeIfAbsent(e.getPath(), k -> new LinkedHashMap<String, Object>()));
            item.putIfAbsent(e.getMethod().toLowerCase(Locale.ROOT), operation(e, usedSchemes));
        }
        root.put("servers", servers.stream().map(s -> Map.of("url", s)).toList());
        root.put("paths", paths);

        Map<String, Object> schemes = new LinkedHashMap<>();
        if (usedSchemes.contains("bearerAuth")) schemes.put("bearerAuth", Map.of("type", "http", "scheme", "bearer", "bearerFormat", "JWT"));
        if (usedSchemes.contains("basicAuth")) schemes.put("basicAuth", Map.of("type", "http", "scheme", "basic"));
        if (usedSchemes.contains("apiKeyAuth")) schemes.put("apiKeyAuth", Map.of("type", "apiKey", "in", "header", "name", "X-API-Key"));
        if (!schemes.isEmpty()) root.put("components", Map.of("securitySchemes", schemes));
        return root;
    }

    private Map<String, Object> operation(ApiEndpoint e, Set<String> usedSchemes) {
        Map<String, Object> op = new LinkedHashMap<>();
        op.put("summary", e.getName());
        if (e.getDescription() != null) op.put("description", e.getDescription());
        op.put("operationId", (e.getMethod() + "_" + e.getService() + e.getPath()).replaceAll("[^A-Za-z0-9]+", "_"));
        op.put("tags", List.of(e.getModule() == null ? e.getService() : e.getModule()));
        if (e.getStatus() == com.apiatlas.model.Enums.EndpointStatus.DEPRECATED) op.put("deprecated", true);
        op.put("x-protocol", e.getProtocol().name());

        List<Map<String, Object>> params = new ArrayList<>();
        Matcher m = PATH_PARAM.matcher(e.getPath());
        while (m.find()) {
            params.add(Map.of("name", m.group(1), "in", "path", "required", true, "schema", Map.of("type", "string")));
        }
        details.queryParams(e.getId()).forEach((k, v) -> params.add(Map.of("name", k, "in", "query", "required", false,
                "schema", Map.of("type", "string"), "example", com.apiatlas.utility.Masker.isSensitiveKey(k) ? "***" : v)));
        if (!params.isEmpty()) op.put("parameters", params);

        if (e.getSampleRequest() != null) {
            boolean json = details.isJson(e.getSampleRequest());
            op.put("requestBody", Map.of("content", Map.of(json ? "application/json" : "text/plain",
                    Map.of("example", details.example(e.getSampleRequest())))));
        }

        Map<String, Object> responses = new LinkedHashMap<>();
        details.responsesByStatus(e.getId()).forEach((status, r) -> responses.put(String.valueOf(status), response(r)));
        if (responses.isEmpty()) responses.put("default", Map.of("description", "No response captured"));
        op.put("responses", responses);

        String scheme = switch (e.getAuthType()) {
            case JWT, OAUTH2 -> "bearerAuth";
            case BASIC -> "basicAuth";
            case API_KEY -> "apiKeyAuth";
            case NONE -> null;
        };
        if (scheme != null) {
            usedSchemes.add(scheme);
            op.put("security", List.of(Map.of(scheme, List.of())));
        }
        return op;
    }

    private Map<String, Object> response(ApiResponse r) {
        Map<String, Object> out = new LinkedHashMap<>();
        out.put("description", "HTTP " + r.getStatusCode());
        Object example = details.example(r.getBody());
        if (example != null) {
            String ct = r.getContentType() != null ? r.getContentType().split(";")[0].trim() : "application/json";
            out.put("content", Map.of(ct, Map.of("example", example)));
        }
        return out;
    }

    @SuppressWarnings("unchecked")
    private static Map<String, Object> castMap(Object o) {
        return (Map<String, Object>) o;
    }
}
