package com.apiatlas.exporter;

import com.apiatlas.model.ApiEndpoint;
import com.apiatlas.model.ApiResponse;
import com.apiatlas.utility.Masker;
import com.apiatlas.utility.PathNormalizer;
import lombok.RequiredArgsConstructor;
import org.springframework.stereotype.Component;

import java.util.*;
import java.util.regex.Pattern;

/** Builds a Postman Collection v2.1 grouped by service. */
@Component
@RequiredArgsConstructor
public class PostmanExporter {
    private static final Pattern PATH_PARAM = Pattern.compile("\\{([^}]+)}");
    private static final Set<String> SKIP_HEADERS = Set.of("host", "content-length", "connection", "cookie", "authorization", "user-agent");

    private final EndpointDetails details;

    public Map<String, Object> build(List<ApiEndpoint> endpoints, String name) {
        Map<String, List<Object>> folders = new LinkedHashMap<>();
        for (ApiEndpoint e : endpoints) {
            folders.computeIfAbsent(e.getService(), k -> new ArrayList<>()).add(item(e));
        }
        List<Object> items = new ArrayList<>();
        folders.forEach((service, list) -> items.add(Map.of("name", service, "item", list)));

        Map<String, Object> root = new LinkedHashMap<>();
        root.put("info", Map.of("name", name, "description", "Generated by API Atlas",
                "schema", "https://schema.getpostman.com/json/collection/v2.1.0/collection.json"));
        root.put("item", items);
        return root;
    }

    private Map<String, Object> item(ApiEndpoint e) {
        String base = PathNormalizer.baseUrl(e.getUrl(), e.getPath());
        String postmanPath = PATH_PARAM.matcher(e.getPath()).replaceAll(":$1");
        List<String> segments = Arrays.stream(postmanPath.split("/")).filter(s -> !s.isEmpty()).toList();
        String host = base.replaceFirst("^[a-zA-Z]+://", "");
        String protocol = base.startsWith("https") ? "https" : "http";

        List<Map<String, String>> query = new ArrayList<>();
        details.queryParams(e.getId()).forEach((k, v) -> query.add(Map.of("key", k, "value", Masker.isSensitiveKey(k) ? "{{" + k + "}}" : v)));
        List<Map<String, String>> variables = new ArrayList<>();
        java.util.regex.Matcher m = PATH_PARAM.matcher(e.getPath());
        while (m.find()) variables.add(Map.of("key", m.group(1), "value", "1"));

        StringBuilder raw = new StringBuilder(base + postmanPath);
        if (!query.isEmpty()) {
            raw.append('?');
            raw.append(String.join("&", query.stream().map(q -> q.get("key") + "=" + q.get("value")).toList()));
        }
        Map<String, Object> url = new LinkedHashMap<>();
        url.put("raw", raw.toString());
        url.put("protocol", protocol);
        url.put("host", List.of(host));
        url.put("path", segments);
        if (!query.isEmpty()) url.put("query", query);
        if (!variables.isEmpty()) url.put("variable", variables);

        List<Map<String, String>> headers = new ArrayList<>();
        details.requestHeaders(e.getId()).forEach((k, v) -> {
            if (!SKIP_HEADERS.contains(k.toLowerCase(Locale.ROOT)) && !k.startsWith(":")) headers.add(Map.of("key", k, "value", v));
        });

        Map<String, Object> request = new LinkedHashMap<>();
        request.put("method", e.getMethod());
        request.put("header", headers);
        request.put("url", url);
        if (e.getDescription() != null) request.put("description", e.getDescription());
        if (e.getSampleRequest() != null) {
            request.put("body", Map.of("mode", "raw", "raw", e.getSampleRequest(),
                    "options", Map.of("raw", Map.of("language", details.isJson(e.getSampleRequest()) ? "json" : "text"))));
        }
        switch (e.getAuthType()) {
            case JWT, OAUTH2 -> request.put("auth", Map.of("type", "bearer",
                    "bearer", List.of(Map.of("key", "token", "value", "{{token}}", "type", "string"))));
            case BASIC -> request.put("auth", Map.of("type", "basic", "basic", List.of(
                    Map.of("key", "username", "value", "{{username}}", "type", "string"),
                    Map.of("key", "password", "value", "{{password}}", "type", "string"))));
            case API_KEY -> request.put("auth", Map.of("type", "apikey", "apikey", List.of(
                    Map.of("key", "key", "value", "X-API-Key", "type", "string"),
                    Map.of("key", "value", "value", "{{apiKey}}", "type", "string"))));
            case NONE -> { }
        }

        List<Object> examples = new ArrayList<>();
        for (ApiResponse r : details.responsesByStatus(e.getId()).values()) {
            Map<String, Object> ex = new LinkedHashMap<>();
            ex.put("name", "HTTP " + r.getStatusCode());
            ex.put("code", r.getStatusCode());
            ex.put("status", "HTTP " + r.getStatusCode());
            ex.put("originalRequest", request);
            ex.put("body", r.getBody() == null ? "" : r.getBody());
            examples.add(ex);
        }
        Map<String, Object> item = new LinkedHashMap<>();
        item.put("name", e.getName());
        item.put("request", request);
        item.put("response", examples);
        return item;
    }
}
